import os from 'os'
import path from 'path'
import fs from 'fs'

export type OSType = 'linux' | 'darwin' | 'win32' | 'wsl'
export type AgentType = 'opencode' | 'claude' | 'cursor' | 'codex' | 'windsurf'

export interface AgentPaths {
  configDir: string
  configFile: string
  skillDir: string
  mcpSection: string
  configFormat: 'json' | 'toml'
  example: string
}

function isWSL(): boolean {
  try {
    return fs.existsSync('/proc/sys/fs/binfmt_misc/WSLInterop') ||
           (fs.existsSync('/proc/version') &&
            fs.readFileSync('/proc/version', 'utf-8').toLowerCase().includes('microsoft'))
  } catch { return false }
}

export function detectOS(): OSType {
  const p = os.platform()
  if (p === 'linux' && isWSL()) return 'wsl'
  if (p === 'linux') return 'linux'
  if (p === 'darwin') return 'darwin'
  if (p === 'win32') return 'win32'
  return 'linux'
}

export function osName(osType: OSType): string {
  const names: Record<OSType, string> = {
    linux: 'Linux', darwin: 'macOS', win32: 'Windows', wsl: 'WSL (Windows)'
  }
  return names[osType]
}

function homeDir(osType: OSType): string {
  if (osType === 'win32') {
    return process.env.USERPROFILE || path.join('C:', 'Users', 'default')
  }
  return process.env.HOME || '/tmp'
}

export function getAgentPaths(agent: AgentType, osType?: OSType): AgentPaths {
  const detected = osType || detectOS()
  const home = homeDir(detected)
  const isWin = detected === 'win32'
  const configRoot = isWin
    ? path.join(home, '.config')
    : path.join(home, '.config')

  const appData = isWin
    ? path.join(home, 'AppData', 'Roaming')
    : home

  switch (agent) {
    case 'opencode':
      return {
        configDir: path.join(configRoot, 'opencode'),
        configFile: path.join(configRoot, 'opencode', 'opencode.json'),
        skillDir: path.join(configRoot, 'opencode', 'skills'),
        mcpSection: 'mcp',
        configFormat: 'json',
        example: 'OpenCode',
      }

    case 'claude':
      return {
        configDir: path.join(home, '.claude'),
        configFile: path.join(home, '.claude', isWin ? 'settings.json' : 'claude_settings.json'),
        skillDir: path.join(home, '.claude', 'skills'),
        mcpSection: 'mcpServers',
        configFormat: 'json',
        example: 'Claude Code',
      }

    case 'cursor':
      return {
        configDir: isWin
          ? path.join(appData, 'Cursor', 'User')
          : path.join(home, '.config', 'cursor'),
        configFile: isWin
          ? path.join(appData, 'Cursor', 'User', 'mcp.json')
          : path.join(home, '.config', 'cursor', 'mcp.json'),
        skillDir: path.join(home, '.cursor', 'skills'),
        mcpSection: 'mcpServers',
        configFormat: 'json',
        example: 'Cursor',
      }

    case 'codex':
      return {
        configDir: path.join(home, '.codex'),
        configFile: path.join(home, '.codex', 'config.toml'),
        skillDir: path.join(home, '.codex', 'skills'),
        mcpSection: 'mcp_servers',
        configFormat: 'toml',
        example: 'Codex',
      }

    case 'windsurf':
      return {
        configDir: path.join(home, '.windsurf'),
        configFile: path.join(home, '.windsurf', 'mcp.json'),
        skillDir: path.join(home, '.windsurf', 'skills'),
        mcpSection: 'mcpServers',
        configFormat: 'json',
        example: 'Windsurf',
      }
  }
}

export function generateAgentConfig(agent: AgentType, mcps: { name: string; command: string; args: string[]; env: Record<string, string>; enabled: boolean }[]): string {
  const enabled = mcps.filter(m => m.enabled)

  switch (agent) {
    case 'opencode': {
      const mcpSection: Record<string, any> = {}
      for (const m of enabled) {
        mcpSection[m.name] = {
          type: 'local',
          command: [m.command, ...m.args],
          enabled: true,
        }
      }
      return JSON.stringify({ mcp: mcpSection }, null, 2)
    }

    case 'claude': {
      const mcpSection: Record<string, any> = {}
      for (const m of enabled) {
        const entry: any = { command: m.command }
        if (m.args.length > 0) entry.args = m.args
        if (Object.keys(m.env).length > 0) entry.env = m.env
        mcpSection[m.name] = entry
      }
      return JSON.stringify({ mcpServers: mcpSection }, null, 2)
    }

    case 'cursor': {
      const mcpSection: Record<string, any> = {}
      for (const m of enabled) {
        const entry: any = { command: m.command }
        if (m.args.length > 0) entry.args = m.args
        if (Object.keys(m.env).length > 0) entry.env = m.env
        mcpSection[m.name] = entry
      }
      return JSON.stringify({ mcpServers: mcpSection }, null, 2)
    }

    case 'codex': {
      let toml = '# Generated by opencode-registry\n[mcp_servers]\n'
      for (const m of enabled) {
        const argsStr = m.args.length > 0 ? `, args = ${JSON.stringify(m.args)}` : ''
        const envStr = Object.keys(m.env).length > 0
          ? `, env = ${JSON.stringify(m.env)}`
          : ''
        toml += `"${m.name}" = { command = "${m.command}"${argsStr}${envStr} }\n`
      }
      return toml
    }

    case 'windsurf':
      return generateAgentConfig('cursor', mcps)

    default:
      return ''
  }
}
